#ifndef FWAK_CPLUG_CONFIG_H
#define FWAK_CPLUG_CONFIG_H

#include "project_config.h"

#define CPLUG_IS_INSTRUMENT FWAK_PLUGIN_IS_INSTRUMENT
#define CPLUG_WANT_GUI FWAK_GUI_NATIVE
#define CPLUG_GUI_RESIZABLE FWAK_GUI_RESIZABLE
#define CPLUG_WANT_MIDI_INPUT FWAK_PLUGIN_WANTS_MIDI_INPUT
#define CPLUG_WANT_MIDI_OUTPUT 0

#define CPLUG_COMPANY_NAME FWAK_COMPANY_NAME
#define CPLUG_COMPANY_EMAIL ""
#define CPLUG_PLUGIN_NAME FWAK_PRODUCT_NAME
#define CPLUG_PLUGIN_URI "https://github.com/mlangens/faust-web-au-kit"
#define CPLUG_PLUGIN_VERSION FWAK_PROJECT_VERSION
#define CPLUG_VST3_CATEGORIES FWAK_VST3_CATEGORIES
#define CPLUG_VST3_TUID_COMPONENT FWAK_VST3_TUID_COMPONENT
#define CPLUG_VST3_TUID_CONTROLLER FWAK_VST3_TUID_CONTROLLER
#define CPLUG_CLAP_ID FWAK_CLAP_ID
#define CPLUG_CLAP_DESCRIPTION FWAK_CLAP_DESCRIPTION
#define CPLUG_CLAP_FEATURES FWAK_CLAP_FEATURES

#define CPLUG_AUV2_VIEW_CLASS FwakAuv2ViewFactory
#define CPLUG_AUV2_VIEW_CLASS_STR "FwakAuv2ViewFactory"

#endif
